[phases.setup]
nixPkgs = ['nodejs', 'openssl']

[phases.install]
cmds = ['npm install']

[phases.build]
cmds = ['npx prisma generate', 'npm run build']

[start]
cmd = 'sh -c "npx prisma migrate deploy && npm run start:prod"'
